# Generated by Django 3.2.6 on 2021-08-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
